### ISSUE TITLE
Unable to install Epsilon

### ISSUE THREAD

**Issue by sblommers** [eclipse/epsilon#55]
I keep getting a repository is not found, seems like GMF tooling is removed?

[2023-10-02 10:51:22] ERROR: org.eclipse.equinox.p2.metadata.repository code=1000 No repository found at http://download.eclipse.org/modeling/gmp/gmf-tooling/updates/releases.
  at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:405)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:119)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.fail(CachingRepositoryManager.java:388)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:279)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:520)
  at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:110)
  at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:105)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$RepositoryLoader$Worker.perform(ProfileTransactionImpl.java:1759)
  at org.eclipse.oomph.util.WorkerPool$Worker.run(WorkerPool.java:437)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by kolovos** [comment]
Yes, this seems to be the case. I've added a request to keep the GMF Tooling update site despite terminating the project here: https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/593

**Comment by kolovos** [comment]
In the meantime, you can install Epsilon from its update site and omit the `Epsilon GMF Integration` feature.

**Comment by sblommers** [comment]
Hi there, thanks for your quick response. It's actually the GMF Integration that I need for Eugenia.

**Comment by kolovos** [comment]
Until this gets fixed, I've [added a warning](https://github.com/eclipse/epsilon-website/commit/24a6e2b364a6a6abf144be916c53726076848f74) to the download page.

<img width="803" alt="image" src="https://github.com/eclipse/epsilon/assets/3584136/8e0e01d0-8f8a-496d-a03c-e01d25ce02f0">

**Comment by kolovos** [comment]
The GMF Tooling update site has been temporarily restored until a longer-term solution can be found.
